import girl1 from "../../public/girls-img/girl1.png";
import girl2 from "../../public/girls-img/girl2.png";
import girl3 from "../../public/girls-img/girl3.png";
import girl4 from "../../public/girls-img/girl4.png";
import girl5 from "../../public/girls-img/girl5.png";
import girl6 from "../../public/girls-img/girl6.png";
import boy1 from "../../public/boys-img/boy1.png";
import boy2 from "../../public/boys-img/boy2.png";
import boy3 from "../../public/boys-img/boy3.png";
import boy4 from "../../public/boys-img/boy4.png";
import boy5 from "../../public/boys-img/boy5.png";
import boy6 from "../../public/boys-img/boy6.png";

const data = [
  {
    id: 1,
    img: girl1,
    name: "රුවන්තිකා ප්‍රභා කුමාරි",
    birthDay: "1989-05-08",
    gender: "ස්ත්‍රී",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "ගුරිවරියක්",
    address: "Kolongoda Obbegoda monaragala",
    district: "මොනරාගල",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 2,
    img: girl2,
    name: "සජානි රුවන්තිකා",
    birthDay: "1994.12.19",
    gender: "ස්ත්‍රී",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "Designer & Developer",
    address: "Kolongoda Obbegoda monaragala",
    district: "Monaragala",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 3,
    img: girl3,
    name: "ඉෂාරා විමලරත්න",
    birthDay: "1993-06-06",
    gender: "ස්ත්‍රී",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "Designer & Developer",
    address: "Kolongoda Obbegoda monaragala",
    district: "ගම්පහ",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 4,
    img: girl4,
    name: "මිනෝදි ලක්රන්දි",
    birthDay: "1996-03-04",
    gender: "ස්ත්‍රී",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "හෙදනිළධාරිනි",
    address: "Kolongoda Obbegoda monaragala",
    district: "කොළඹ ",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 5,
    img: girl5,
    name: "අමායා දිසානායක",
    birthDay: "2001-06-26",
    gender: "ස්ත්‍රී",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "පෙරපාසැල් ගුරිවරියක්",
    address: "Kolongoda Obbegoda monaragala",
    district: "දඹුල්ල",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 6,
    img: girl6,
    name: "ෂෙහාරා ප්‍රනාන්දු",
    birthDay: "1990-05-13",
    gender: "ස්ත්‍රී",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "Designer & Developer",
    address: "Kolongoda Obbegoda monaragala",
    district: "පේරාදේණිය",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 7,
    img: boy1,
    name: "ලහිරු මධුසංඛ",
    birthDay: "1997-02-01",
    gender: "ස්ත්‍රී",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "ව්‍යාපාර(ජංගම දුරකථන",
    address: "Kolongoda Obbegoda monaragala",
    district: "වැල්ලවාය",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 8,
    img: boy2,
    name: "ප්‍රගීත් මල්ෂාන්",
    birthDay: "2001-03-10",
    gender: "පුරුෂ",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "යුධ හමුදාවේ සෙවාව",
    address: "Kolongoda Obbegoda monaragala",
    district: "පේරාදේණිය",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 9,
    img: boy3,
    name: "විරාජ් මීගස්කඩ",
    birthDay: "1992-11-06",
    gender: "පුරුෂ",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "පශු වෛද්‍ය නිළධාරී",
    address: "Kolongoda Obbegoda monaragala",
    district: "අනුරාධපුර",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 10,
    img: boy4,
    name: "H.A සුජිත් ",
    birthDay: "1990-01-15",
    gender: "පුරුෂ",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "වනජීවි රක්ෂණ දෙ.පා",
    address: "Kolongoda Obbegoda monaragala",
    district: "මොනරාගල",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 11,
    img: boy5,
    name: "අශේන් සාරංග",
    birthDay: "1994-01-04",
    gender: "පුරුෂ",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "ටෝකියෝ සිමෙන්ති නිෂ්පාදන ආයතනයක  රසායනාගාර කාර්මික",
    address: "Kolongoda Obbegoda monaragala",
    district: "ගල්ගමුව",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
  {
    id: 12,
    img: boy6,
    name: "දමිදු ප්‍රභාත්",
    birthDay: "2000-11-12",
    gender: "පුරුෂ",
    age: 20,
    height: { feet: 4, inch: 9 },
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: "සිංහල",
    religion: "Buddhist",
    caste: "Guru",
    job: "ඇගලුම්හලක සුපර්වයිසර්",
    address: "Kolongoda Obbegoda monaragala",
    district: "පේරාදේණිය",
    maritalStatus: "None",
    monthlyIncome: 100000,
  },
];

export default data;
